In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [24]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__);

2.1.0+cu121


# Introduction to Fundamentals

Resources


1.   Pytorch doc : https://pytorch.org/docs/stable/torch.html
2.   Follow along doc : https://www.learnpytorch.io/00_pytorch_fundamentals/#what-is-pytorch
3. Yt vid: https://www.youtube.com/watch?v=Z_ikDlimN6A&list=PLlx-Yw-SvHWrFWBUF2OyV064Gy9gayKU4&index=25&t=85s



**Intoduction to Tensor **

Creating a tensor

In [25]:
#scalar
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [26]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
print("Tensor : " ,x_data)

Tensor :  tensor([[1, 2],
        [3, 4]])


NumPy's Ndarray

In [27]:
data = [[1,2],[3,4]]
np_array = np.array(data)
x_np =torch.from_numpy(np_array)
print("Ndarray : ", x_np)

Ndarray :  tensor([[1, 2],
        [3, 4]])


In [28]:
x_one = torch.ones_like(x_data)
print(f"One Tensor : \n {x_one}\n")

x_rand = torch.rand_like(x_data, dtype=torch.float) #override the datatype of x_data
print(f"Random Tensor : \n {x_rand}\n")

One Tensor : 
 tensor([[1, 1],
        [1, 1]])

Random Tensor : 
 tensor([[0.5208, 0.2006],
        [0.8707, 0.4050]])



In [29]:
x_data.ndim

2

In [30]:
x_rand.ndim
x_data[1]
x_data[0]

tensor([1, 2])

In [31]:
TENSOR = torch.tensor([[[1,2,3,5],
                       [3,4,5,6],
                       [6,7,8,8]]])
TENSOR

tensor([[[1, 2, 3, 5],
         [3, 4, 5, 6],
         [6, 7, 8, 8]]])

In [32]:
TENSOR.ndim

3

In [33]:
TENSOR.shape

torch.Size([1, 3, 4])

***Random Tensors***

In [34]:
random_tensor = torch.rand(2,3,9,4)
random_tensor

tensor([[[[0.3749, 0.7398, 0.7255, 0.4117],
          [0.0881, 0.1920, 0.9316, 0.0767],
          [0.1940, 0.0216, 0.7799, 0.1709],
          [0.7770, 0.5863, 0.0062, 0.4409],
          [0.1869, 0.6498, 0.1541, 0.9053],
          [0.4036, 0.7784, 0.5334, 0.6556],
          [0.5538, 0.2428, 0.5156, 0.1752],
          [0.5587, 0.6042, 0.9309, 0.1826],
          [0.4727, 0.9488, 0.2675, 0.8835]],

         [[0.4135, 0.0137, 0.8478, 0.6774],
          [0.8477, 0.2029, 0.9333, 0.4570],
          [0.0717, 0.7212, 0.6576, 0.4634],
          [0.7998, 0.4665, 0.6479, 0.3978],
          [0.8386, 0.7131, 0.0079, 0.2877],
          [0.8639, 0.0964, 0.7014, 0.9744],
          [0.3532, 0.0866, 0.5989, 0.6838],
          [0.8219, 0.3962, 0.4185, 0.1397],
          [0.5133, 0.7571, 0.0604, 0.6406]],

         [[0.9379, 0.3862, 0.7659, 0.5599],
          [0.5206, 0.3220, 0.7938, 0.3134],
          [0.1015, 0.9600, 0.8599, 0.0396],
          [0.2637, 0.6881, 0.8451, 0.7803],
          [0.0554, 0.4768, 0

In [35]:
random_tensor.ndim

4

**Zeroes and Ones**

In [36]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [37]:
ones = torch.ones(size=(3,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

***Range of Tensor***

In [38]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
scalar = torch.arange(start=0, end=100, step=10)
scalar

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])



---


***Tensor Datatypes***

**NOTE:** Tensor datatype is one of the 3 big error you can run into with PyTorch & deep learning:


1.   Tensors not right datatype
2.   Tensors not right shape
3.   Tensors not on the right device


In [40]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float32, #type of datatype of tensor (for eg: float16, float32, complex32, complex16)
                               device= None, # #what device your tensor on
                               requires_grad=False) #whether or not to track gradients with this tensor's operations
float_32_tensor

tensor([3., 6., 9.])

In [41]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [42]:
tensor_add = float_32_tensor + float_16_tensor
tensor_add

tensor([ 6., 12., 18.])

In [43]:
tensor_subtract = float_32_tensor - float_16_tensor
tensor_subtract

tensor([0., 0., 0.])

In [44]:
tensor_multiply = float_32_tensor * float_16_tensor
tensor_multiply

tensor([ 9., 36., 81.])

In [45]:
tensor_divide = float_32_tensor / float_16_tensor
tensor_divide

tensor([1., 1., 1.])

In [46]:
#Manipulation of Tensor

vector = torch.tensor([1,2,3])
vector

tensor([1, 2, 3])

In [47]:
torch.add(vector, 10)

tensor([11, 12, 13])

In [48]:
torch.sub(vector, 10)

tensor([-9, -8, -7])

In [49]:
torch.mul(vector, 10)

tensor([10, 20, 30])

#Matrix Multiplication


There are two types of multiplication in pytorch

1. Element-wise
2.Matrix Multiplication



In [50]:
#Element-wise multiplication

matrix = torch.tensor([[1,2,3],
                       [5,6,7],
                       [8,6,3]])

In [51]:
print(f"Equals : {matrix * matrix}")

Equals : tensor([[ 1,  4,  9],
        [25, 36, 49],
        [64, 36,  9]])


In [52]:
#Matrix Multipllication
%%time
torch.matmul(matrix, matrix)

CPU times: user 1.56 ms, sys: 56 µs, total: 1.61 ms
Wall time: 4.01 ms


tensor([[35, 32, 26],
        [91, 88, 78],
        [62, 70, 75]])

In [53]:
tensor_1 = torch.rand(3,2)
tensor_1

tensor([[0.6098, 0.4776],
        [0.1082, 0.1016],
        [0.6368, 0.9430]])

In [54]:
tensor_2 = torch.rand(2,3)
tensor_2

tensor([[0.0853, 0.2283, 0.4143],
        [0.2987, 0.4539, 0.8207]])

In [55]:
torch.matmul(tensor_1, tensor_2) * 0.899

tensor([[0.1750, 0.3200, 0.5794],
        [0.0356, 0.0637, 0.1152],
        [0.3021, 0.5155, 0.9329]])

***Transpose of Matrix***

In [56]:
tensor_1 = torch.tensor([[1,2],
                       [3,4],
                       [5,6]])
tensor_1

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [57]:
tensor_2 = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
tensor_2

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [58]:
tensor_3 = tensor_1.T
tensor_3

tensor([[1, 3, 5],
        [2, 4, 6]])

In [59]:
torch.matmul(tensor_1, tensor_3)
#but we cannot do
#torch.matmul(tensor_1, tensor_2)
#as the inner dimensions are not the same

tensor([[ 5, 11, 17],
        [11, 25, 39],
        [17, 39, 61]])

Tensor Aggregation

In [60]:
x = torch.arange(0,100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [61]:
torch.max(x), torch.min(x)

(tensor(90), tensor(0))

In [62]:
torch.mean(x) #you cannot computer mean with long datatype

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
torch.mean(x.type(torch.float16)) , x.type(torch.float32).mean()
#apparently this works for float32 float16, not for complex32,int32 etc

In [ ]:
torch.sum(x) , x.sum()

***Finding the position min and max***

In [ ]:
#Find the position in tensor that has the minimum value with argmin() ->
#return that position
x.argmin()

In [ ]:
x.argmax()

##Reshaping, stacking, squeezing, unsqueezing tensors

1. Reshaping - reshape an input tensor to a defined shape
2. View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
3. Stacking - combine mutiple tensors on top of each other(vstack) or side by side
(hstack)
4. Squeeze - removes all `1` dimensions from a tensor
5. Unsqueeze - add a `1` dimension to a target tensor
6. Permute - Return a view of the input with dimensiosn permuted in a certain way

In [ ]:
x = torch.arange(1., 10.)
print(x)
print(x.shape)

In [ ]:
x_reshape = x.reshape(3,3)  # 3*3 =shape([9])
x_reshape

In [ ]:
x_reshaped = x.reshape(1,9) # 1*9 = 9
print(x_reshaped)
print(x_reshaped.shape)

In [ ]:
x_reshaped = x.reshape(9,1) #transposes the matrix # 9*1 = 9
print(x_reshaped)
print(x_reshaped.shape)

In [77]:
#change the view
z = x.view(1,9)
print(z)
print(z.shape)

RuntimeError: shape '[1, 9]' is invalid for input of size 3

**Changing z changes x (because a view of a tensor shares the same memory as the original tensor)**

Its like reference in C++

In [76]:
z[:,0] = 5
print("z = ", z)
print("x = ", x)

IndexError: too many indices for tensor of dimension 1

In [75]:
x.shape,x

(torch.Size([3]), tensor([1, 2, 3]))

In [74]:
#stack tensor on top of each other (vstack)
x_stacked = torch.stack([x,x,x,x], dim=0) # 4 x stacked as rows
x_stacked

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [73]:
x_stacked = torch.stack([x,x,x,x], dim=1) # 4 transposed x stacked side by side
x_stacked

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])

In [72]:
x_stacked = torch.stack([x,x,x,x], dim=2)
x_stacked

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

In [70]:
y = torch.tensor([[1,2],
                  [2,3]])
y, y.shape

(tensor([[1, 2],
         [2, 3]]),
 torch.Size([2, 2]))

In [71]:
x_stacked = torch.stack([y,y,y,y], dim=0)
x_stacked

tensor([[[1, 2],
         [2, 3]],

        [[1, 2],
         [2, 3]],

        [[1, 2],
         [2, 3]],

        [[1, 2],
         [2, 3]]])

In [69]:
x_stacked = torch.stack([y,y,y,y], dim=1)
x_stacked

tensor([[4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6]])

In [68]:
x_stacked = torch.stack([y,y,y,y], dim=2)
x_stacked

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

In [67]:
x_stacked = torch.stack([y,y,y,y], dim=3)
x_stacked

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 3)

In [66]:
#vstack
x = torch.tensor([1,2,3])
y = torch.tensor([4,5,6])
v = torch.vstack((x,y))

In [63]:
 h = torch.hstack((x,y))
 h

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90,  4,  5,  6])

In [64]:
#torch.squeeze - removes all single dimensions from a target dimension
d = torch.tensor([[1,2,3,4,5,6]])
d, d.shape

(tensor([[1, 2, 3, 4, 5, 6]]), torch.Size([1, 6]))

In [65]:
d.squeeze().shape

torch.Size([6])

In [84]:
print(f"Original Tensor = {d}")
print(f"Squeezed size {d.shape}")
print(f"Squeezed tensor = {d.squeeze()}")
print(f"Squeezed size {d.squeeze().shape}")
print(f"Unsqueezed tensor = {d.unsqueeze(dim=0)}")
print(f"Unsqueezed size {d.unsqueeze(dim=0).shape}")


Original Tensor = tensor([[1, 2, 3, 4, 5, 6]])
Squeezed size torch.Size([1, 6])
Squeezed tensor = tensor([1, 2, 3, 4, 5, 6])
Squeezed size torch.Size([6])
Unsqueezed tensor = tensor([[[1, 2, 3, 4, 5, 6]]])
Unsqueezed size torch.Size([1, 1, 6])


In [89]:
#torch.permute - rearrange the dimensions
x_original = torch.rand(size=(224,224,3)) #[height,width,color_channel]

#permute the orignal tensor to rearrange the axis (or dim ) order
x_permuted = x_original.permute(2,0,1,)

print(f"Original tensor {x_original}and shape{x_original.shape}")
print(f"Permuted tensor {x_permuted}and shape{x_permuted.shape}")

Original tensor tensor([[[8.7164e-01, 4.2146e-01, 4.7637e-01],
         [4.8485e-01, 9.7746e-02, 6.9943e-01],
         [3.1102e-01, 8.0674e-01, 2.6560e-01],
         ...,
         [5.5288e-01, 9.9917e-01, 6.7739e-01],
         [1.5898e-01, 8.7316e-01, 2.3478e-01],
         [4.0912e-01, 1.6640e-01, 6.2332e-01]],

        [[3.8111e-01, 3.3052e-01, 6.9192e-01],
         [6.9834e-01, 5.3640e-01, 1.7339e-01],
         [7.4359e-01, 1.8779e-01, 8.3945e-01],
         ...,
         [7.0636e-01, 6.4826e-02, 6.7856e-01],
         [8.5020e-01, 1.7169e-01, 5.6316e-01],
         [5.0206e-01, 4.5778e-01, 6.2563e-01]],

        [[3.8047e-01, 8.6475e-01, 4.0397e-01],
         [5.7879e-01, 6.6073e-01, 7.4097e-01],
         [2.3052e-01, 7.0887e-01, 9.8171e-01],
         ...,
         [3.7305e-01, 8.7440e-01, 3.7316e-01],
         [1.9698e-02, 9.5084e-01, 1.1078e-02],
         [2.1864e-01, 2.4984e-01, 1.0882e-01]],

        ...,

        [[2.2904e-01, 2.2968e-01, 5.6836e-01],
         [5.2006e-02, 8.5367e

In [91]:
x_original[0,0,0] = 0.69
x_permuted = x_original.permute(2,0,1,)
print(x_original[0,0,0,])
print(x_permuted[0,0,0,])
#hence we see that the change is copied to the x_permuted
#thus permuted uses a view of the original and any changed done to the original
#is reflected to the copy also

tensor(0.6900)
tensor(0.6900)


*Indexing(selecting data from tensor)*

In [93]:
#create a tensor
tensor = torch.arange(1,10).reshape(1,3,3)
tensor, tensor.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [97]:
x = torch.tensor([[[1,2,3],
                  [4,5,6],
                  [7,8,9]]])

In [102]:
x.shape

torch.Size([1, 3, 3])

In [99]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [98]:
x[0][0]

tensor([1, 2, 3])

In [100]:
x[0][0][0]

tensor(1)

In [101]:
x[0][2][2]

tensor(9)

In [116]:
#get all values of 0th and 1st dimensions but only index 1 of 2nd simension
x[:,:,1]

tensor([2, 5, 8])

In [104]:
x[:, 1, :]

tensor([[4, 5, 6]])

In [106]:
x[0, :, :]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [114]:
x[0, :, 1]
#this is different from x[:,:,1]

tensor([2, 5, 8])

In [118]:
x[:,:,1].shape, x[0,:,1].shape

(torch.Size([1, 3]), torch.Size([3]))

In [119]:
#we can use squeeze to remove that single dimension
x[:,:,1].squeeze()

tensor([2, 5, 8])

In [126]:
x[:, 2, :]  #return the row of index 2

tensor([[7, 8, 9]])

In [127]:
x[:, :, 2] # returns the column of index 2

tensor([[3, 6, 9]])

# Pytorch tensors & Numpy

***NumPy is a Popular scientific Python numerical computing library***

And because of this, Pytorch has a functionality to interact with it



*   Data in Numpy, convert to Pytorch tensor -> `torch.from_numpy(ndarray)`
*   Pytorch tensor -> NumPy -> `torch.Tensor.numpy()`



In [128]:
#NumPy array to tensor
import torch
import numpy as np

In [133]:
array = np.arange(1.0,10.0)
tensor = torch.from_numpy(array)
print(f"NumPy Ndarray = {array}")
print(f"Torch Tensor = {tensor}")

NumPy Ndarray = [1. 2. 3. 4. 5. 6. 7. 8. 9.]
Torch Tensor = tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)


In [134]:
#the different default datatypes of the torch and Numpy
array.dtype

dtype('float64')

In [136]:
torch.arange(1.0,10.0).dtype

torch.float32

In [137]:
#changing value of array
array = array * 2
array, tensor

(array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [141]:
#Tensor to NumPy array
tensor = torch.rand(3,3)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([[0.1276, 0.2635, 0.9239],
         [0.5924, 0.2088, 0.8970],
         [0.2994, 0.6046, 0.7641]]),
 array([[0.12762749, 0.26347625, 0.9239258 ],
        [0.59237844, 0.2087689 , 0.8970485 ],
        [0.2993846 , 0.6045991 , 0.76413953]], dtype=float32))

In [142]:
#changing the tensor
tensor = tensor + 1
tensor, numpy_tensor
#Result : remains the same

(tensor([[1.1276, 1.2635, 1.9239],
         [1.5924, 1.2088, 1.8970],
         [1.2994, 1.6046, 1.7641]]),
 array([[0.12762749, 0.26347625, 0.9239258 ],
        [0.59237844, 0.2087689 , 0.8970485 ],
        [0.2993846 , 0.6045991 , 0.76413953]], dtype=float32))

##Reproducbility (trying to take random out of random tensors)

In short how a neural network learns:

`start with random numbers -> tensor operations performed -> update the random numbers to fit the model -> Repeat the steps`

However in a reproducable model, you dont want much randomness, which could harm the reproducable nature of the model. Thats when we use `**random.seed()**`
Essentially what random seed does is "flavour" the randomness

In [4]:
import torch
rand_tensor_A = torch.rand(3,3)
rand_tensor_B = torch.rand(3,3)

print(f"First Tensor : {rand_tensor_A}")
print(f"Second Tensor :  {rand_tensor_B}")

print(f"Are first and second tensors equal? {rand_tensor_A == rand_tensor_B}")

First Tensor : tensor([[0.5392, 0.0733, 0.2653],
        [0.3810, 0.6985, 0.8332],
        [0.9905, 0.7336, 0.5899]])
Second Tensor :  tensor([[0.9219, 0.1640, 0.3922],
        [0.4289, 0.8049, 0.8127],
        [0.4085, 0.6557, 0.4769]])
Are first and second tensors equal? tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])


In [12]:
#Set random seed
RANDOM_SEED = 1
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(f"First Tensor : {random_tensor_C}")
print(f"Second Tensor :  {random_tensor_D}")
print(f"Are first and second tensors equal? {random_tensor_C == random_tensor_D}")


First Tensor : tensor([[0.7576, 0.2793, 0.4031, 0.7347],
        [0.0293, 0.7999, 0.3971, 0.7544],
        [0.5695, 0.4388, 0.6387, 0.5247]])
Second Tensor :  tensor([[0.7576, 0.2793, 0.4031, 0.7347],
        [0.0293, 0.7999, 0.3971, 0.7544],
        [0.5695, 0.4388, 0.6387, 0.5247]])
Are first and second tensors equal? tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra Resource : https://pytorch.org/docs/stable/notes/randomness.html#reproducibility

##Running tensors and PyTorch objects on GPUs

Ways to use GPU for Neural Network models


1.   Use Google Colab(upgrade to pro)
2.   Use your own GPU
3.   Use cloud computing

Note for AMD Radeon GPUs : ROCm - Radeon Open Compute Ecosystem, is largely how AMD is competing against Nvidia’s CUDA technology. As for the programming language you use, they expose HIP - Heterogeneous-Computing Interface for Portability. HIP is really nice as it’s basically just CUDA with all of the cudaFunction style functions expressed as hipFunction. (such as cudaMemcpy -> hipMemcpy). You can also use OpenCL


In [1]:
!nvidia-smi

Sat Mar  9 20:19:32 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   50C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [4]:
#check for GPU access with Pytorch
import torch
torch.cuda.is_available()

True

In [5]:
#Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [6]:
torch.cuda.device_count()

1

Resource : https://pytorch.org/docs/stable/notes/cuda.html#cuda-semantics

In [7]:
 #create a tensor on CPU
 tensor = torch.tensor([1,2,3], device = "cpu")

 print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [8]:
#move tensor to GPU
tensor_gpu = tensor.to(device)
tensor_gpu

tensor([1, 2, 3], device='cuda:0')

In [10]:
tensor_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [11]:
#moving tensors back to cpu
#Numpy uses CPU, so you have to convert a tensor in torch which uses GPU, to NumPy
tensor_cpu = tensor_gpu.cpu().numpy()
tensor_cpu

array([1, 2, 3])

# Excercises

In [14]:
#2.
import torch
tensor_a = torch.rand(7,7)
tensor_a

tensor([[0.4983, 0.8325, 0.8085, 0.8758, 0.5964, 0.5477, 0.1767],
        [0.9329, 0.4916, 0.7577, 0.3801, 0.5020, 0.4205, 0.1882],
        [0.3682, 0.8156, 0.8378, 0.6170, 0.3742, 0.7087, 0.6228],
        [0.7901, 0.2783, 0.5779, 0.6383, 0.4467, 0.0920, 0.2017],
        [0.9131, 0.5071, 0.9669, 0.9372, 0.8518, 0.2294, 0.0689],
        [0.6026, 0.5756, 0.8832, 0.5108, 0.0438, 0.9081, 0.7872],
        [0.3933, 0.7103, 0.9679, 0.9508, 0.0028, 0.1934, 0.7736]])

In [15]:

#3.
tensor_b = torch.rand(1,7)
tensor_b

tensor([[0.7715, 0.5888, 0.8611, 0.7604, 0.0681, 0.5020, 0.5787]])

In [16]:
#since for matrix multiplication the inner dimensions must match so we have to transpose tensor_b and then multiply
torch.matmul(tensor_a, tensor_b.T)

tensor([[2.6545],
        [2.3048],
        [2.6965],
        [1.9498],
        [2.7613],
        [2.8671],
        [2.8230]])

In [21]:
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
tensor_a = torch.rand(7,7)

torch.manual_seed(RANDOM_SEED)
tensor_b = torch.rand(1,7)

print(f"Tensor A : {tensor_a}")
print(f"Tensor B : {tensor_b}")

torch.matmul(tensor_a, tensor_b.T)

Tensor A : tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
Tensor B : tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])


tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [ ]:
#5
GPU_RANDOM_SEED = 1234
torch.cuda.random_seed(GPU_RANDOM_SEED)


In [ ]:
#6.
device = "cuda"
GPU_RANDOM_SEED = 1234
torch.cuda.random_seed(GPU_RANDOM_SEED)
tensor_a = torch.rand(2,3).to(device)

torch.cuda.random_seed(GPU_RANDOM_SEED)
tensor_b = torch.rand(2,3).to(device)



In [25]:
#7.
tensor_out = torch.matmul(tensor_a, tensor_b.T)  #since we need to match the inner dimensions


In [26]:
#8.
torch.max(tensor_out), torch.min(tensor_out)

(tensor(1.6838), tensor(0.8279))

In [27]:
#9.
tensor_out.argmax(), tensor_out.argmin()

(tensor(3), tensor(4))

In [28]:
#10.
tensor = torch.rand(1,1,1,10)
tensor

tensor([[[[0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689, 0.2939,
           0.5185, 0.6977]]]])

In [38]:
RAND_SEED = 7
torch.manual_seed(RAND_SEED)
tensor_2 = tensor.squeeze()
tensor_2, tensor_2.shape

(tensor([0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689, 0.2939, 0.5185,
         0.6977]),
 torch.Size([10]))

In [39]:
#or
torch.manual_seed(RAND_SEED)
tensor_2 = tensor.reshape(10)
tensor_2, tensor_2.shape

(tensor([0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689, 0.2939, 0.5185,
         0.6977]),
 torch.Size([10]))